// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.iyp.model;

import com.iyp.model.CardType;
import com.iyp.model.CardTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CardTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CardTypeDataOnDemand: @Component;
    
    private Random CardTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<CardType> CardTypeDataOnDemand.data;
    
    public CardType CardTypeDataOnDemand.getNewTransientCardType(int index) {
        CardType obj = new CardType();
        return obj;
    }
    
    public CardType CardTypeDataOnDemand.getSpecificCardType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CardType obj = data.get(index);
        String id = obj.getId();
        return CardType.findCardType(id);
    }
    
    public CardType CardTypeDataOnDemand.getRandomCardType() {
        init();
        CardType obj = data.get(rnd.nextInt(data.size()));
        String id = obj.getId();
        return CardType.findCardType(id);
    }
    
    public boolean CardTypeDataOnDemand.modifyCardType(CardType obj) {
        return false;
    }
    
    public void CardTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = CardType.findCardTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CardType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CardType>();
        for (int i = 0; i < 10; i++) {
            CardType obj = getNewTransientCardType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
