// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myhome.model;

import com.myhome.model.CardTypeDataOnDemand;
import com.myhome.model.CardTypeIntegrationTest;
import com.myhome.service.CardTypeService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CardTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CardTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CardTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CardTypeIntegrationTest: @Transactional;
    
    @Autowired
    CardTypeDataOnDemand CardTypeIntegrationTest.dod;
    
    @Autowired
    CardTypeService CardTypeIntegrationTest.cardTypeService;
    
    @Test
    public void CardTypeIntegrationTest.testCountAllCardTypes() {
        Assert.assertNotNull("Data on demand for 'CardType' failed to initialize correctly", dod.getRandomCardType());
        long count = cardTypeService.countAllCardTypes();
        Assert.assertTrue("Counter for 'CardType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CardTypeIntegrationTest.testFindCardType() {
        CardType obj = dod.getRandomCardType();
        Assert.assertNotNull("Data on demand for 'CardType' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CardType' failed to provide an identifier", id);
        obj = cardTypeService.findCardType(id);
        Assert.assertNotNull("Find method for 'CardType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CardType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CardTypeIntegrationTest.testFindAllCardTypes() {
        Assert.assertNotNull("Data on demand for 'CardType' failed to initialize correctly", dod.getRandomCardType());
        long count = cardTypeService.countAllCardTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'CardType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CardType> result = cardTypeService.findAllCardTypes();
        Assert.assertNotNull("Find all method for 'CardType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CardType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CardTypeIntegrationTest.testFindCardTypeEntries() {
        Assert.assertNotNull("Data on demand for 'CardType' failed to initialize correctly", dod.getRandomCardType());
        long count = cardTypeService.countAllCardTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CardType> result = cardTypeService.findCardTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CardType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CardType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CardTypeIntegrationTest.testFlush() {
        CardType obj = dod.getRandomCardType();
        Assert.assertNotNull("Data on demand for 'CardType' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CardType' failed to provide an identifier", id);
        obj = cardTypeService.findCardType(id);
        Assert.assertNotNull("Find method for 'CardType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCardType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CardType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CardTypeIntegrationTest.testUpdateCardTypeUpdate() {
        CardType obj = dod.getRandomCardType();
        Assert.assertNotNull("Data on demand for 'CardType' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CardType' failed to provide an identifier", id);
        obj = cardTypeService.findCardType(id);
        boolean modified =  dod.modifyCardType(obj);
        Integer currentVersion = obj.getVersion();
        CardType merged = cardTypeService.updateCardType(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CardType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CardTypeIntegrationTest.testSaveCardType() {
        Assert.assertNotNull("Data on demand for 'CardType' failed to initialize correctly", dod.getRandomCardType());
        CardType obj = dod.getNewTransientCardType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CardType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CardType' identifier to be null", obj.getId());
        try {
            cardTypeService.saveCardType(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'CardType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CardTypeIntegrationTest.testDeleteCardType() {
        CardType obj = dod.getRandomCardType();
        Assert.assertNotNull("Data on demand for 'CardType' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CardType' failed to provide an identifier", id);
        obj = cardTypeService.findCardType(id);
        cardTypeService.deleteCardType(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'CardType' with identifier '" + id + "'", cardTypeService.findCardType(id));
    }
    
}
