// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myhome.model;

import com.myhome.model.Card;
import com.myhome.model.CardDataOnDemand;
import com.myhome.model.CardTypeDataOnDemand;
import com.myhome.model.UserDataOnDemand;
import com.myhome.service.CardService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CardDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CardDataOnDemand: @Component;
    
    private Random CardDataOnDemand.rnd = new SecureRandom();
    
    private List<Card> CardDataOnDemand.data;
    
    @Autowired
    CardTypeDataOnDemand CardDataOnDemand.cardTypeDataOnDemand;
    
    @Autowired
    UserDataOnDemand CardDataOnDemand.userDataOnDemand;
    
    @Autowired
    CardService CardDataOnDemand.cardService;
    
    public Card CardDataOnDemand.getNewTransientCard(int index) {
        Card obj = new Card();
        setPrice(obj, index);
        setScheduledDate(obj, index);
        return obj;
    }
    
    public void CardDataOnDemand.setPrice(Card obj, int index) {
        Long price = new Integer(index).longValue();
        obj.setPrice(price);
    }
    
    public void CardDataOnDemand.setScheduledDate(Card obj, int index) {
        Date scheduledDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setScheduledDate(scheduledDate);
    }
    
    public Card CardDataOnDemand.getSpecificCard(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Card obj = data.get(index);
        Long id = obj.getId();
        return cardService.findCard(id);
    }
    
    public Card CardDataOnDemand.getRandomCard() {
        init();
        Card obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return cardService.findCard(id);
    }
    
    public boolean CardDataOnDemand.modifyCard(Card obj) {
        return false;
    }
    
    public void CardDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = cardService.findCardEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Card' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Card>();
        for (int i = 0; i < 10; i++) {
            Card obj = getNewTransientCard(i);
            try {
                cardService.saveCard(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
